name: Build Docker

on:
  push:
    branches:
      - "main"

jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login to Dockerhub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - shell: bash
        env:
          USERNAME:  ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          ls -l 
          docker build . -t $USERNAME/github-docker-integration:latest
          docker push $USERNAME/github-docker-integration -a
          
          echo "The image has been pushed!"